# Frontend
base.url=http://localhost:3000
api.base.url=http://localhost:8000

# Browser
browser=chrome
headless=false
implicit.wait=10
explicit.wait=15

# Database
db.url=jdbc:postgresql://localhost:5433/cinema_app
db.user=postgres
db.password=Trang@051203

# Test data
test.data.email.prefix=qa_test_
